# https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name                        = "win32_security_playground"
version                     = "0.0.0-git"
publish                     = false
authors                     = ["MaulingMonkey <git@maulingmonkey.com>"]
edition                     = "2021"
license                     = "Apache-2.0 OR MIT"
readme                      = "Readme.md"

[dependencies]
abibool                     = "0.5.2"
abistr.version              = "0.2.0-rc1"
abistr.features             = ["widestring-0-4"] # &str -> TryIntoAsOptCStr<u16>

[target.'cfg(windows)'.dependencies]
winapi.version = "0.3"
winapi.features = [
    # shared
    "bcrypt",
    "sddl",
    "winerror",

    # um
    "debugapi",
    "errhandlingapi",
    "handleapi",
    "heapapi",
    "lsalookup",
    "memoryapi",
    "ntlsa",
    "processthreadsapi",
    "securitybaseapi",
    "synchapi",
    "winbase",
    "winnt",
    "winuser",
]
