# https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members                     = ["crates/*"]

[package]
name                        = "win32_security_playground"
version                     = "0.0.0-git"
publish                     = false
authors                     = ["MaulingMonkey <git@maulingmonkey.com>"]
edition                     = "2021"
license                     = "Apache-2.0 OR MIT"
readme                      = "Readme.md"

[profile.dev]
panic                       = "abort"
lto                         = true

[profile.release]
panic                       = "abort"
lto                         = true

[features]
default                     = ["std"]
std                         = ["sandbox/std"]

[dependencies]
sandbox.path                = "crates/sandbox"

#abistr.version              = "0.2.0-rc2"
abistr.default-features     = false
abistr.git                  = "https://github.com/MaulingMonkey/abistr"
abistr.rev                  = "be791b8c6f78fe2399d3f2d0549c43cbe5d74d04"

[target.'cfg(windows)'.dependencies]
winapi.version = "0.3"
winapi.features = [
    # um
    "synchapi",
]
