# https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members                     = ["crates/*"]
exclude                     = ["crates/no-std"] # separate workspace

[profile.dev]
panic                       = "abort"
lto                         = true

[profile.release]
panic                       = "abort"
lto                         = true
