[target.x86_64-pc-windows-msvc]
rustflags = [
    "-Ccontrol-flow-guard=checks",
    "-Ctarget-feature=+crt-static"
]

[target.i686-pc-windows-msvc]
rustflags = [
    "-Ccontrol-flow-guard=checks",
    "-Ctarget-feature=+crt-static"
]
